module.exports = {
  extends: ['@commitlint/config-angular'],
  rules: {
    // Angular preset omits `chore`; project Conventional Commits allow it.
    'type-enum': [
      2,
      'always',
      [
        'build',
        'ci',
        'chore',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'web',
        'web-e2e',
        'shared-types',
        'workspace',
        'libs-data-access',
        'libs-state',
        'libs-feature-list',
        'libs-card-list',
        'libs-device-detail',
        'libs-platform-specific-examples',
        'sync-devices',
        'sync-example-upstreams',
        'generate-platform-examples',
        'validate-platform-examples',
        'ci',
        'mcp',
      ],
    ],
  },
};
